# Generated by Django 4.0.1 on 2022-01-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_based_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multichoicequestion',
            options={'verbose_name_plural': 'Multi Choice Questions'},
        ),
    ]
