# Generated by Django 4.0.1 on 2022-02-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admission',
            new_name='AdmissionForm',
        ),
        migrations.AlterModelOptions(
            name='admissionform',
            options={'verbose_name_plural': 'Admission Form'},
        ),
    ]
