# Generated by Django 4.0.1 on 2022-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolportal', '0002_rename_admission_admissionform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='schoolasset',
            name='date_acquired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolasset',
            name='size',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
