# Generated by Django 4.0.1 on 2022-02-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_account_type_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
