# Generated by Django 3.2.9 on 2021-11-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211112_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, default='https://facebook.com/', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='instagram',
            field=models.URLField(blank=True, default='https://youtube.com/', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com/', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.URLField(blank=True, default='https://twitter.com/', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='youtube',
            field=models.URLField(blank=True, default='https://linkedin.com/', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='share_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='ShareImage',
        ),
    ]
