# Generated by Django 3.2.9 on 2021-11-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211126_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name_plural': 'Seo'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AlterField(
            model_name='seo',
            name='metaDescription',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='seo',
            name='metaTitle',
            field=models.TextField(max_length=200),
        ),
    ]
