# Generated by Django 3.2.9 on 2021-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_article_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_count',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[(0, 'News'), (1, 'Research'), (2, 'Event')], default='', max_length=32, unique=True),
        ),
    ]
