# Generated by Django 3.2.9 on 2021-11-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211128_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecount',
            name='article_count',
            field=models.IntegerField(default=0),
        ),
    ]
