# Generated by Django 3.2.9 on 2021-11-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_articlecount_article_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecount',
            name='article_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
