# Generated by Django 4.0.1 on 2022-01-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_articlecount_article_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='share_image',
        ),
    ]
