# Generated by Django 4.0.1 on 2022-01-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_article_image_remove_author_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seo',
        ),
    ]
