# Generated by Django 4.0.1 on 2022-02-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_news_remove_article_author_remove_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('content', models.TextField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
