# Generated by Django 4.0.1 on 2022-02-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumni',
        ),
    ]
