# Generated by Django 4.0.1 on 2022-02-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0002_delete_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nin',
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], max_length=10, null=True),
        ),
    ]
