# Generated by Django 4.0.1 on 2022-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0005_newsletter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
