# Generated by Django 4.0.1 on 2022-02-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0007_rename_payment_invoice_remove_result_school_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
